shivanshsinghx365/Computer-Science-Resources

CONTRIBUTING.md
added guidelines on how to contribute to the project
=> Created a CONTRIBUTING.md

System Design/System Design.md
=> Added System Design Resources

Python/Learning-Material
Added link to an excellent course for learning Python.
=> added learning material

Java/learn_java.md
some popular java tutorials and courses have been added
=> added resources for learning java

Java/practice_java.md
added practice sites to practice java questions and programs
=> created practice_java

Cpp/learn_cpp.md
resources to learn c++ have been added
=> added learn_cpp

Cpp/practice_cpp.md
=> added practice_cpp.md

Blockchain/resources-blockchain
This is my PR for issue#7 as part of Hacktoberfest. I've added resources for blockchain development, including Youtube tutorials, Documentation and Books and Communities and Developer Groups to be part of.
=> Resolved Issue #7 as part of Hacktoberfest 2022

Code Snippets and Oneliners/Djikstra's Algorithm- Shortest path.cpp, Code Snippets and Oneliners/Kahn's Algorithm-Topological sort.cpp, Code Snippets and Oneliners/Kruskal's Algorithm-Minimum Spanning Tree.cpp, Code Snippets and Oneliners/Prim's Algorithm- Minimum spanning Tree.cpp
This is my PR for Issue#6 for Hacktoberfest 2022. I've added code snippets for 4 Graph Algorithms in c++ under the Code snippets folder. @shivanshsinghx365
=> Resolved Issue #6 as part of Hacktoberfest 2022

Computer Networking/computer-networking-resources
This is my PR for issue #21 as part of Hacktoberfest 2022. I've added youtube tutorials, free online courses on reputed platforms and books for reference @shivanshsinghx365
=> Added resources for Computer Networking- Resolved issue #21

DBMS/DBMS-Resources
I've added resources for users to learn DBMS. I've included youtube tutorials, free online courses and books for reference that would help users to crack interviews and exams. Please review and merge them as part of Hacktoberfest @shivanshsinghx365
=> Added DBMS resources for placements and university exams as part of Hacktoberfest

CONTRIBUTING.md, DevOps/Resources.md, README.md
I would like to request the maintainers to accept this PR as a part of the hacktoberfest 2022, and also label my PR as a hacktoberfest, I am experienced in doing open source and I provide genuine prs to open source projects
=> Updated the README.MD & CONTRIBUTING.MD and also added various resources in DevOps to get started with

Code Snippets and Oneliners/Quicksort Python One-liner.py
Added Quicksort Python One-liner on Code Snippets and Oneliners File
for Hacktoberfest 2022
=> Added Quicksort Python One-liner

DevOps/Roadmap.md
I have added a DevOps Roadmap for beginners
=> added Roadmap for DevOps

Flutter/.gitkeep, Flutter/Resources.md, Flutter/Roadmaps.md, Game Development/.gitkeep, Game Development/Resources.md
Created 2 new folders for flutter and game development and added study resources and roadmaps for the same.
Signed-off-by: Gokul Eswaran <gokul465eswaran@gmail.com>
=> adds resources and roadmaps for flutter dev and game dev

WebDev/Backend Development Resources
I've added youtube tutorials, documentation and free online courses for users to learn Backend Web Development as part of Hacktoberfest 2022 @shivanshsinghx365
=> Added Resources for Backend Web Development as part of Hacktoberfest

Code Snippets and Oneliners/C/CircularQueue.c
Added Circular Queue Implementation in C under Code Snippets folder.
=> Add Circular Queue Implementation in C

WebDev/Frontend Development Resources
Added many resources for front-end webdesign and UI/UX based challanges.
=> Included frontend web resources

OS/OS-Resources.md
renamed the repo to a Markdown for easier visualization and added more resources
=> Update and rename OS-Resources to OS-Resources.md

AI-ML/Resources.md, Android/Android.md, Blockchain/resources-blockchain, Cheat Sheets/CheatSheets.md, Competitive Programming/Resources.md, Computer Networking/computer-networking-resources, Computer Organization/computer-organization-resources, DBMS/DBMS-Resources, Data-Science/Data Science.md, DevOps/Resources.md
I have included resources for the different categories organized in the repo. I hope this PR is to your standard.
=> Added resources under multiple categories

Code Snippets and Oneliners/C/Stack.c
I have included a code snippet of a Stack implementation in C.
=> Added Stack implementation in C

Internships & Job Portals/portals.md
=> Fixed run lychee_action error

Cheat Sheets/CheatSheets.md, Interviews/interview.md
- add system design primer and design patterns cheatsheet
- add 64 common interview questions and answers
=> add design cheatsheets and hr interview questionnaire

AI-ML/Machine-Learning/readme.md, AI-ML/Resources.md
Added a link into Resources.MD file. This link redirects to the blog I wrote that explains The Machine Learning Techniques in simple words.
=> Modified Resources.MD file

Code Snippets and Oneliners/C/doublylinkedlist.c
added code for insertion in doubly linked list
=> added code for insertion in doubly linked list

Code Snippets and Oneliners/C/avltree.c
Added code for insertion,deletion and preorder traversal in AVL tree
=> added a code for AVL tree

Python/Learning-Material
Added a very useful website for python tutorials
=> added learnpython website

Code Snippets and Oneliners/FenwickTree.cpp
It can handle range sum and point update.
=> Created Fenwick Tree Data structure
